RD /s /q .\Build\Debug\cs
RD /S /Q .\Build\Debug\da
RD /S /Q .\Build\Debug\de
RD /S /Q .\Build\Debug\es
RD /S /Q .\Build\Debug\fa
RD /S /Q .\Build\Debug\fi
RD /S /Q .\Build\Debug\fr
RD /S /Q .\Build\Debug\it
RD /S /Q .\Build\Debug\ja
RD /S /Q .\Build\Debug\ko
RD /S /Q .\Build\Debug\mk
RD /S /Q .\Build\Debug\nl
RD /S /Q .\Build\Debug\pl
RD /S /Q .\Build\Debug\pt
RD /S /Q .\Build\Debug\pt-br
RD /S /Q .\Build\Debug\ru
RD /S /Q .\Build\Debug\sv
RD /S /Q .\Build\Debug\tr
RD /S /Q .\Build\Debug\zh-CN
RD /S /Q .\Build\Debug\zh-Hans
RD /S /Q .\Build\Debug\zh-Hant
